import Navbar from "@/components/Navbar";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-[rgba(96,72,255,0.08)]">
        <Navbar />
        {children}
      </body>
    </html>
  );
}
